### PR TITLE
Updater

### PR DESCRIPTION
**Pull request by JakePickle**

### CODE REVIEW

**Comment by joshreed13** [comment]
Hey, we just merged another pull request and now yours conflicts. Can you pull the new changes down and resolve the conflicts. Look up how to add commits to a pull request.

**Comment by tymorrow** [comment]
Found the link: [How to update a pull request - StackOverflow](http://stackoverflow.com/questions/9790448/how-to-update-a-pull-request)

**Comment by JakePickle** [comment]
It is working now but, is not styled with MahApps

**Comment by tymorrow** [comment]
Are you waiting to merge this @joshreed13?

**Pull request merged**
